// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mfa_queries.sql

package database

import (
	"context"
	"database/sql"
)

const createNewRecoveryCode = `-- name: CreateNewRecoveryCode :one
INSERT INTO recovery_codes (user_id, code_hash)
VALUES ($1, $2)
RETURNING id, created_at
`

type CreateNewRecoveryCodeParams struct {
	UserID   int64
	CodeHash []byte
}

type CreateNewRecoveryCodeRow struct {
	ID        int64
	CreatedAt sql.NullTime
}

func (q *Queries) CreateNewRecoveryCode(ctx context.Context, arg CreateNewRecoveryCodeParams) (CreateNewRecoveryCodeRow, error) {
	row := q.db.QueryRowContext(ctx, createNewRecoveryCode, arg.UserID, arg.CodeHash)
	var i CreateNewRecoveryCodeRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
