// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID               int64
	FirstName        string
	LastName         string
	Email            string
	PasswordHash     []byte
	PhoneNumber      string
	Activated        sql.NullBool
	Version          sql.NullInt32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LastLogin        time.Time
	ProfileCompleted sql.NullBool
	Dob              time.Time
	Address          sql.NullString
	CountryCode      sql.NullString
	CurrencyCode     sql.NullString
}
