package main

import (
	"expvar"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strconv"

	"go.uber.org/zap"
)

// ---------------------------------------------------------------------------
// Prometheus /metrics endpoint.
//
// We already collect every operational signal we care about as expvars on
// /debug/vars (rate limiter, request log, portfolio analysis, response-by-
// status). The JSON shape there is fine for ad-hoc inspection but unscrapable
// by Prometheus, which expects the line-oriented text exposition format.
//
// Rather than pull in github.com/prometheus/client_golang and re-instrument
// every call site, this file implements a small adapter that:
//
//   - walks the existing expvar registry once per scrape
//   - matches each name against an explicit allow-list (knownMetrics below)
//   - emits standards-compliant text exposition (HELP / TYPE / sample lines)
//
// The allow-list is deliberate. expvar publishes "cmdline" and a large
// "memstats" struct by default, neither of which is useful in this format and
// some of which (memstats) is a multi-level map that does not flatten cleanly.
// Anything not in the allow-list is skipped, so adding a new expvar that
// should appear on /metrics also requires a one-line table change here. The
// friction is intentional: the /metrics surface is operator-facing, not a
// debug dump.
//
// Naming sanitisation: Prometheus restricts metric names to the regex
// [a-zA-Z_:][a-zA-Z0-9_:]*. Our pre-existing total_processing_time_μs uses
// a non-ASCII micro sign; this file remaps it to total_processing_time_us in
// the Prom output. The JSON name on /debug/vars stays the same so existing
// dashboards or scripts pointing at expvar are unaffected.
// ---------------------------------------------------------------------------

// metricsContentType is the standard Prometheus text exposition Content-Type
// header value (version 0.0.4). Keep it as the canonical string Prom servers
// negotiate against; do not abbreviate.
const metricsContentType = "text/plain; version=0.0.4; charset=utf-8"

// metricKind controls whether a given expvar is exposed as a Prom counter
// (monotonic) or gauge (snapshot). Histograms and summaries are out of scope
// — none of the existing expvars carry the per-bucket data those types
// require.
type metricKind int

const (
	counterKind metricKind = iota
	gaugeKind
)

func (k metricKind) String() string {
	switch k {
	case counterKind:
		return "counter"
	case gaugeKind:
		return "gauge"
	default:
		return "untyped"
	}
}

// metricMeta describes one row of the allow-list. promName lets us rename
// during emission (used for the μs sanitisation case); when empty, the
// expvar name is reused verbatim.
type metricMeta struct {
	promName string
	kind     metricKind
	help     string
}

// knownMetrics is the curated set of expvars exposed via /metrics. Adding a
// row here is what makes a metric scrapable; removing a row hides it without
// touching the underlying instrumentation. Names line up 1:1 with the
// expvar.New* declarations elsewhere in cmd/api.
var knownMetrics = map[string]metricMeta{
	// Request lifecycle (logging.go).
	"request_log_total":          {kind: counterKind, help: "Total HTTP requests observed by the structured request logger."},
	"request_log_4xx_total":      {kind: counterKind, help: "Total HTTP requests that completed with a 4xx status code."},
	"request_log_5xx_total":      {kind: counterKind, help: "Total HTTP requests that completed with a 5xx status code."},
	"request_id_generated_total": {kind: counterKind, help: "Total X-Request-ID values generated by the requestID middleware (inbound header was missing or invalid)."},
	"request_id_rejected_total":  {kind: counterKind, help: "Total inbound X-Request-ID headers rejected for being malformed and replaced with a freshly generated value."},

	// Rate limiter (middleware.go).
	"rate_limiter_allowed_total":      {kind: counterKind, help: "Total rate-limiter checks that allowed the request."},
	"rate_limiter_denied_total":       {kind: counterKind, help: "Total rate-limiter checks that denied the request with HTTP 429."},
	"rate_limiter_redis_errors_total": {kind: counterKind, help: "Total Redis errors observed while consulting the rate-limiter bucket."},
	"rate_limiter_fail_open_total":    {kind: counterKind, help: "Total requests admitted because the rate limiter could not reach Redis (fail-open)."},
	"rate_limiter_disabled_total":     {kind: counterKind, help: "Total requests that bypassed the rate limiter because it was disabled in config."},

	// Portfolio analysis (portfolio_analysis.go).
	"portfolio_analysis_runs_total":           {kind: counterKind, help: "Total portfolio-analysis pipeline runs started."},
	"portfolio_analysis_errors_total":         {kind: counterKind, help: "Total portfolio-analysis pipeline runs that ended in error."},
	"portfolio_singleflight_collapsed_total":  {kind: counterKind, help: "Total upstream fetches saved by the singleflight dedup wrapper."},
	"portfolio_analysis_duration_ms":          {kind: gaugeKind, help: "Wall-clock duration of the most recent portfolio-analysis run, in milliseconds."},
	"portfolio_analysis_workers_active":       {kind: gaugeKind, help: "Per-asset workers currently in flight inside the portfolio-analysis pipeline."},
	"portfolio_analysis_workers_max_observed": {kind: gaugeKind, help: "High-water mark for concurrent per-asset workers since process start."},

	// Global request metrics from the metrics middleware (middleware.go).
	"total_requests_received": {kind: counterKind, help: "Total HTTP requests received at the outermost middleware."},
	"total_responses_sent":    {kind: counterKind, help: "Total HTTP responses written by the outermost middleware."},
	"total_processing_time_μs": {
		// Prom rejects the non-ASCII micro sign in the metric name; rename in
		// the exposition only. The expvar key is unchanged for /debug/vars.
		promName: "total_processing_time_us",
		kind:     counterKind,
		help:     "Cumulative response-handling time across all requests, in microseconds.",
	},

	// Process-level gauges (main.go publishMetrics).
	"goroutines": {kind: gaugeKind, help: "Currently running goroutines (runtime.NumGoroutine snapshot)."},
	"timestamp":  {kind: gaugeKind, help: "Unix timestamp at which this scrape was served. Useful to detect stale exporters."},
}

// labeledMaps lists expvar.Map values whose keys should be promoted to a
// single Prom label. The Map name itself stays as the metric name; each map
// entry becomes one labeled sample line. Right now this only covers the
// status-code breakdown, but the table form means new maps can be added with
// one line.
var labeledMaps = map[string]struct {
	promName string
	kind     metricKind
	label    string
	help     string
}{
	"total_responses_sent_by_status": {
		kind:  counterKind,
		label: "code",
		help:  "Total HTTP responses written, broken down by status code.",
	},
}

// stringInfoMetrics promotes a small set of expvar.String values to Prom
// "info"-style metrics: a gauge always set to 1, with the string content
// carried as a label. This is the canonical way to expose build identity in
// the Prom ecosystem (e.g. node_exporter's node_uname_info).
var stringInfoMetrics = map[string]struct {
	promName string
	label    string
	help     string
}{
	"version": {
		promName: "optivest_build_info",
		label:    "version",
		help:     "Build identifier of the running OptiVest process. Always 1; the version is carried in the label.",
	},
}

// prometheusMetricsHandler serves the Prometheus text exposition for the
// curated set of expvars. Unauthenticated by design — the deployment is
// expected to scope this endpoint to the internal scrape network (see
// SECURITY.md). If an operator needs to gate it, wrap the handler in the
// existing rate limiter / auth chain at the routes layer; nothing in this
// file assumes anonymous access.
func (app *application) prometheusMetricsHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", metricsContentType)
	w.Header().Set("Cache-Control", "no-store")
	if err := writePrometheusExposition(w); err != nil {
		// At this point headers are already flushed; we cannot meaningfully
		// upgrade to a 5xx response. Just record the failure on the request
		// logger so the operator notices.
		app.loggerFromRequest(r).Error("metrics: failed to write exposition", zap.Error(err))
	}
}

// writePrometheusExposition is the pure, testable core. It walks expvar.Do
// once, accumulates per-metric sample lines, then emits HELP/TYPE/sample
// blocks in deterministic name order. Returning io.Writer errors lets the
// caller log them; in practice the http.ResponseWriter rarely fails partway
// through a small response, but bubbling up keeps this honest.
func writePrometheusExposition(w io.Writer) error {
	// Buffer per metric so we can emit HELP/TYPE/sample lines together. Maps
	// and Strings can produce multiple samples per metric; collecting them
	// keyed by promName lets us output a single HELP/TYPE pair regardless.
	buckets := make(map[string]*metricBucket)

	expvar.Do(func(kv expvar.KeyValue) {
		if meta, ok := knownMetrics[kv.Key]; ok {
			promName := meta.promName
			if promName == "" {
				promName = kv.Key
			}
			val, ok := scalarString(kv.Value)
			if !ok {
				return
			}
			b := getOrCreateBucket(buckets, promName, meta.kind, meta.help)
			b.samples = append(b.samples, fmt.Sprintf("%s %s", promName, val))
			return
		}
		if meta, ok := labeledMaps[kv.Key]; ok {
			promName := meta.promName
			if promName == "" {
				promName = kv.Key
			}
			m, ok := kv.Value.(*expvar.Map)
			if !ok {
				return
			}
			b := getOrCreateBucket(buckets, promName, meta.kind, meta.help)
			m.Do(func(inner expvar.KeyValue) {
				val, ok := scalarString(inner.Value)
				if !ok {
					return
				}
				b.samples = append(b.samples, fmt.Sprintf(
					"%s{%s=%q} %s",
					promName, meta.label, inner.Key, val,
				))
			})
			return
		}
		if meta, ok := stringInfoMetrics[kv.Key]; ok {
			s, ok := kv.Value.(*expvar.String)
			if !ok {
				return
			}
			b := getOrCreateBucket(buckets, meta.promName, gaugeKind, meta.help)
			b.samples = append(b.samples, fmt.Sprintf(
				"%s{%s=%q} 1",
				meta.promName, meta.label, s.Value(),
			))
			return
		}
	})

	names := make([]string, 0, len(buckets))
	for name := range buckets {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		b := buckets[name]
		// Sort samples within a metric so the output is byte-stable across
		// scrapes — easier to diff in tests and easier to spot drift in
		// dashboards that snapshot the raw text.
		sort.Strings(b.samples)
		if _, err := fmt.Fprintf(w, "# HELP %s %s\n", name, b.help); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "# TYPE %s %s\n", name, b.kind); err != nil {
			return err
		}
		for _, sample := range b.samples {
			if _, err := fmt.Fprintf(w, "%s\n", sample); err != nil {
				return err
			}
		}
	}
	return nil
}

type metricBucket struct {
	kind    metricKind
	help    string
	samples []string
}

func getOrCreateBucket(buckets map[string]*metricBucket, name string, kind metricKind, help string) *metricBucket {
	if b, ok := buckets[name]; ok {
		return b
	}
	b := &metricBucket{kind: kind, help: help}
	buckets[name] = b
	return b
}

// ---------------------------------------------------------------------------
// /debug/vars curated handler.
//
// The default expvar.Handler walks every published var and emits "cmdline"
// (a JSON array of os.Args) by default. The rejectSecretFlags startup gate
// (see main.go) makes it impossible to BOOT the binary with a credential-
// bearing flag, so the practical leak is small today. But:
//
//   - cmdline still echoes deployment topology (paths to envvar files,
//     non-default flag values like -portfolio-worker-limit=12) that an
//     unauthenticated /debug/vars caller has no need to see.
//   - The startup gate is a recent control. Any operator who downgrades
//     past the gate, or runs a forked build, would re-expose the flags
//     without realizing it. Belt-and-braces here keeps the leak shut on
//     both ends.
//
// memstats, goroutines, version, and the curated counters defined in
// publishMetrics + logging.go pass through unchanged. If a future expvar
// publishes a value whose marshaled form might itself include secrets,
// this is the choke point to filter it.
// ---------------------------------------------------------------------------

// debugVarsBlocklist is the set of expvar names this handler refuses to
// emit on /debug/vars. The behavior mirrors the inverse of metrics.go's
// allowlist for /metrics: there we only emit what we explicitly know is
// safe; here we emit everything except what we explicitly know leaks.
var debugVarsBlocklist = map[string]struct{}{
	"cmdline": {},
}

// debugVarsHandler is the curated /debug/vars handler. It produces JSON
// matching the default expvar.Handler shape (an unsorted top-level
// object) minus any keys in debugVarsBlocklist. The format is
// intentionally identical so existing tooling (operator scripts that
// curl /debug/vars and grep, ad-hoc dashboards) continues to work.
func (app *application) debugVarsHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	if _, err := io.WriteString(w, "{\n"); err != nil {
		return
	}
	first := true
	expvar.Do(func(kv expvar.KeyValue) {
		if _, blocked := debugVarsBlocklist[kv.Key]; blocked {
			return
		}
		if !first {
			if _, err := io.WriteString(w, ",\n"); err != nil {
				return
			}
		}
		first = false
		fmt.Fprintf(w, "%q: %s", kv.Key, kv.Value)
	})
	_, _ = io.WriteString(w, "\n}\n")
}

// scalarString renders an expvar.Var to its text exposition value. Int and
// Float marshal directly; expvar.Func is invoked and its result coerced.
// Anything else returns ok=false, which the caller treats as "skip this
// sample" — consistent with the explicit allow-list philosophy of this file.
func scalarString(v expvar.Var) (string, bool) {
	switch x := v.(type) {
	case *expvar.Int:
		return x.String(), true
	case *expvar.Float:
		return x.String(), true
	case expvar.Func:
		raw := x()
		switch n := raw.(type) {
		case int:
			return fmt.Sprintf("%d", n), true
		case int32:
			return fmt.Sprintf("%d", n), true
		case int64:
			return fmt.Sprintf("%d", n), true
		case uint:
			return fmt.Sprintf("%d", n), true
		case uint32:
			return fmt.Sprintf("%d", n), true
		case uint64:
			return fmt.Sprintf("%d", n), true
		case float32:
			return strconv.FormatFloat(float64(n), 'g', -1, 32), true
		case float64:
			return strconv.FormatFloat(n, 'g', -1, 64), true
		}
	}
	return "", false
}
